FROM ubuntu:16.04

# Pick up some TF dependencies
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
        tensorflow-model-server \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

WORKDIR "~/"
