FROM nvidia/cuda:8.0-cudnn5-devel

# Pick up some TF dependencies
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
        python3-pip \
        git \
        wget \
        python3 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY requirements_gpu.txt /tmp/requirements_gpu.txt

RUN pip3 --no-cache-dir install -r /tmp/requirements_gpu.txt

# TensorBoard
EXPOSE 6006
# IPython
EXPOSE 8888

WORKDIR "~/"
